# Display the first 3 rows and last 2 rows of the DataFrame.

In [1]:
import pandas as pd
df = pd.read_csv('students.csv')
print('First 3 Rows')
df.head(3)

First 3 Rows

    Name  Age  Marks  Gender      City
0   John   20   85.0    Male  New York
1  Alice   21   92.0  Female    London
2    Bob   19   45.0    Male     Paris

In [2]:
print('Last 2 rows')
df.tail(2)

Last 2 rows

    Name  Age  Marks  Gender   City
10  Noah   24   55.0    Male  Tokyo
11   Ava   21   99.0  Female  Paris