# Create separate columns for each City from a City column.

In [10]:
import pandas as pd
df = pd.read_csv('students.csv')
df

       Name  Age  Marks  Gender      City
0      John   20   85.0    Male  New York
1     Alice   21   92.0  Female    London
2       Bob   19   45.0    Male     Paris
3      Emma   22    NaN  Female    London
4     David   20  110.0    Male  New York
5    Sophia   23   78.0  Female     Paris
6   Michael   21  150.0    Male     Tokyo
7    Olivia   20   65.0  Female    London
8      John   20   85.0    Male  New York
9      Liam   22    NaN    Male    Berlin
10     Noah   24   55.0    Male     Tokyo
11      Ava   21   99.0  Female     Paris

In [11]:
city_column = pd.get_dummies(df['City'])
df = pd.concat([df, city_column], axis = 1)
df

,Name,Age,Marks,Gender,City,Berlin,London,New York,Paris,Tokyo
0,John,20,85.0,Male,New York,False,False,True,False,False
1,Alice,21,92.0,Female,London,False,True,False,False,False
2,Bob,19,45.0,Male,Paris,False,False,False,True,False
3,Emma,22,NaN,Female,London,False,True,False,False,False
4,David,20,110.0,Male,New York,False,False,True,False,False
5,Sophia,23,78.0,Female,Paris,False,False,False,True,False
6,Michael,21,150.0,Male,Tokyo,False,False,False,False,True
7,Olivia,20,65.0,Female,London,False,True,False,False,False
8,John,20,85.0,Male,New York,False,False,True,False,False
9,Liam,22,NaN,Male,Berlin,True,False,False,False,False
10,Noah,24,55.0,Male,Tokyo,False,False,False,False,True
11,Ava,21,99.0,Female,Paris,False,False,False,True,False